### ISSUE TITLE
[docs] background description docs

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/cleisthenes#15]
**Subject**
docs for basic concept to understand this project

**Detail**
docs for about membership protocol, gossip style protocol, etc
I want to write about below subject for background
if anyone want to write docs about basic docs, plz comment in this issue. 
Then i'll assign you to that item

- [ ] Membership protocol - @hea9549 
- [ ] Gossip style protocol - @boohyunsik 
- [ ] Swim protocol

**Comment by boohyunsik** [comment]
I want to write about gossip protocol!

**Comment by hea9549** [comment]
@boohyunsik i updated issue!
