### ISSUE TITLE
[docs] PBFT documentations

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/cleisthenes#4]
Based on this [youtube](https://www.youtube.com/watch?v=Q0xYCN-rvUs ) plz think about how to implement PBFT protocol.

### Write DOCUMENTATION.md based on this page
Plz write down your name before doing your job

- [ ] page 12 >> @zeroFruit 
- [ ] page 13 >> @zeroFruit 
- [ ] page 14
- [ ] page 15
- [ ] page 16
- [ ] page 17
- [ ] page 18
- [ ] page 19
- [ ] page 20
- [ ] page 21
- [ ] page 22
- [ ] page 23
- [ ] page 24
- [ ] page 29
- [ ] page 30

**Comment by hihiboss** [comment]
@hyolin97 @boohyunsik
