### ISSUE TITLE
[log] suggest logging system

### ISSUE THREAD

**Issue by AgwaB** [DE-labtory/cleisthenes#47]
**Subject**
logging system

**Proposal Detail**
How about use logging library? I think it is important to log when use network (Especially, in p2p system!)
Maybe it is future work... i suggest some logging library! 

**Reference**
- https://github.com/sirupsen/logrus
- https://github.com/uber-go/zap

- https://github.com/gogap/aop
This is one of concept of spring : AOP (Aspect-Oriented Programming). I used this usefully when debug. just suggestion :)

**Comment by zeroFruit** [comment]
# Log format

## suggest

suggest log format

```
{
  # common
  level: string <"error" | "warn" | "info" | "debug">
  comp: string <"hb" | "acs" | "te" | "rbc" | "bba">
  msg: string
  ts: timestamp (YYYY-MM-dd HH:mm:ss)

  # metadata
  ... 
}
```
