### ISSUE TITLE
[Marshaling] marshal and unmarshal message 

### ISSUE THREAD

**Issue by AgwaB** [DE-labtory/cleisthenes#92]
we need marshal and unmarshal function in in each `request.go`

**Comment by hihiboss** [comment]
I want to do this!

**Comment by AgwaB** [comment]
@hihiboss maybe this issue will close soon. because our struct's filed is simple so now i think it dosen't need a function.

**Comment by hihiboss** [comment]
@AgwaB Ok.. .bye...
