### ISSUE TITLE
[conn] using 8080 port

### ISSUE THREAD

**Issue by GunHee5719** [DE-labtory/cleisthenes#99]
**Subject**

**Proposal Detail**
On conn_test.go and comm_test.go, @hihiboss mentioned that 

```Port 8080 is often used. For example, tomcat(web server) uses 8080 as its default port. So, I recommend to change the port number``` 

So what do you think about fixing the existing test cases on that files?

**Comment by hea9549** [comment]
why don't you use util function like this,

``` go
func GetAvailablePort(startPort int) int {
	portNumber := startPort
	for {
		strPortNumber := strconv.Itoa(portNumber)
		lis, Err := net.Listen("tcp", "127.0.0.1:"+strPortNumber)

		if Err == nil {
			lis.Close()
			return portNumber
		}

		portNumber++

	}
}
```

**Comment by GunHee5719** [comment]
Good. I'll use that function at test case for broadcaster.

Then how about test case for GrpcConnection and GrpcServer? @AgwaB @zeroFruit

**Comment by zeroFruit** [comment]
Lgtm!
